HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Fri, 31 Jul 2026 10:41:11 GMT
Keep-Alive: timeout=4
Proxy-Connection: keep-alive
Server: openresty
Vary: Accept-Encoding
Vary: Accept-Encoding
X-Powered-By: PHP/7.3.9

      <section>
        <h2>Add note</h2>
        <form action="add.php" method="POST">
          <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="e.g. What is Haifuri?">
          </div>
          <div class="form-group">
            <label for="body">Body</label>
            <textarea class="form-control" id="body" name="body" placeholder="e.g. Haifuri (High School Fleet) is an anime."></textarea>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </section>