HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Fri, 31 Jul 2026 10:41:10 GMT
Keep-Alive: timeout=4
Proxy-Connection: keep-alive
Server: openresty
Vary: Accept-Encoding
Vary: Accept-Encoding
X-Powered-By: PHP/7.3.9

<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function get_notes() in /var/www/html/pages/notes.php:2
Stack trace:
#0 {main}
  thrown in <b>/var/www/html/pages/notes.php</b> on line <b>2</b><br />
